/**
 * TWA Weather Data Marketplace — Tailwind theme
 * Generated by design-system from ux/tokens.json.
 * scaffold-frontend copies this to the repo root. Tailwind v4 @theme mapping
 * of the CSS variables in tokens.css so utilities resolve to the token layer.
 */
import type { Config } from "tailwindcss";

export default {
  darkMode: ["selector", '[data-theme="dark"]'],
  content: ["./index.html", "./src/**/*.{ts,tsx,js,jsx,html}"],
  theme: {
    extend: {
      colors: {
        bg: "var(--bg)",
        "bg-subtle": "var(--bg-subtle)",
        surface: "var(--surface)",
        "surface-2": "var(--surface-2)",
        border: "var(--border)",
        "border-strong": "var(--border-strong)",
        fg: "var(--fg)",
        "fg-muted": "var(--fg-muted)",
        "fg-subtle": "var(--fg-subtle)",
        accent: "var(--accent)",
        "accent-hover": "var(--accent-hover)",
        "accent-fg": "var(--accent-fg)",
        "accent-subtle": "var(--accent-subtle)",
        "accent-subtle-fg": "var(--accent-subtle-fg)",
        premium: "var(--premium)",
        "premium-subtle": "var(--premium-subtle)",
        "premium-fg": "var(--premium-fg)",
        success: "var(--success)",
        "success-subtle": "var(--success-subtle)",
        warn: "var(--warn)",
        "warn-subtle": "var(--warn-subtle)",
        danger: "var(--danger)",
        "danger-subtle": "var(--danger-subtle)",
        "danger-fg": "var(--danger-fg)",
        info: "var(--info)",
        ring: "var(--ring)",
      },
      fontFamily: {
        display: "var(--font-display)",
        sans: "var(--font-body)",
        mono: "var(--font-mono)",
      },
      borderRadius: {
        xs: "var(--r-xs)",
        sm: "var(--r-sm)",
        md: "var(--r-md)",
        lg: "var(--r-lg)",
        xl: "var(--r-xl)",
      },
      boxShadow: {
        sm: "var(--shadow-sm)",
        md: "var(--shadow-md)",
        lg: "var(--shadow-lg)",
        focus: "var(--shadow-focus)",
      },
      transitionTimingFunction: { brand: "var(--ease)" },
      transitionDuration: { fast: "120ms", base: "180ms", slow: "260ms" },
    },
  },
  plugins: [],
} satisfies Config;
